# Generated by Django 4.2.16 on 2025-06-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
